preload=~/.config/hypr/wallpapers/black.png
preload=~/.config/hypr/wallpapers/bg_wallpaper.png
wallpaper=eDP-1,~/.config/hypr/wallpapers/bg_wallpaper.png
wallpaper=HDMI-A-2,~/.config/hypr/wallpapers/bg_wallpaper.png
fit=2

